// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import CommentFormController from "./comment_form_controller"
application.register("comment-form", CommentFormController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import YoutubeController from "./youtube_controller"
application.register("youtube", YoutubeController)
